services:
  neo4j:
    image: neo4j:latest
    container_name: 'devneo4j'
    environment:
        - NEO4J_AUTH=neo4j/P@ssw0rd
    volumes:
      - '.data/neo4j-data:/data'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  data_loader:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: 'devservice-loader'
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: 'bolt://neo4j:7687'
    command:
      - poetry
      - run
      - python
      - -m
      - service.loader

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: 'devservice'
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8000/docs || exit 1
      interval: 5s
      timeout: 10s
      retries: 60
      start_period: 3s
    environment:
      NEO4J_URI: 'bolt://neo4j:7687'
